# -*- coding: utf-8 -*-
"""Lab3_Q1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-EcfPanVKVQAftWrrGO_iqEHQvWtMfpy
"""

class VaccumCleaner:
    def __init__(self, initial_location, environment,rule_table):
        self.location = initial_location
        self.environment = environment
        self.rule_table=rule_table
        self.direction = 0  # 0 for A -> B -> C, 1 for C -> B -> A
        self.rooms = sorted(list(environment.keys())) # Ensure consistent room order

    def sensors(self):
        """receive the state of the current location."""
        return self.environment[self.location]

    def choose_action(self):
        """Chooses an action based on the current perception."""
        current_state = self.sensors()
        return self.rule_table[current_state]

    def clean(self):
        """Cleans the current location."""
        self.environment[self.location] = 'Clean'
        print(f"Location {self.location} is now Clean.")

    def move(self):
        """Moves the vacuum cleaner to the next location, changing direction at ends."""
        current_index = self.rooms.index(self.location)

        if self.direction == 0:  # Moving A -> B -> C
            if current_index < len(self.rooms) - 1:
                self.location = self.rooms[current_index + 1]
            else:  # change direction and move back one step
                self.direction = 1
                self.location = self.rooms[current_index - 1] if len(self.rooms) > 1 else self.rooms[current_index]
        else:  # Moving C -> B -> A
            if current_index > 0:
                self.location = self.rooms[current_index - 1]
            else:  # Reached the first room, change direction and move forward one step
                self.direction = 0
                self.location = self.rooms[current_index + 1] if len(self.rooms) > 1 else self.rooms[current_index]

        print(f"Moved to location {self.location}.")

Environment={
    'A': 'Dirty',
    'B': 'Clean',
    'C': 'Dirty'
    }
rule_table = {
    'Dirty': 'clean',
    'Clean': 'move'
}

init_loc='B'
my_vaccum=VaccumCleaner(init_loc,Environment,rule_table)
Environment

print("Agent's Decision Rule Table:")
print(rule_table)

class simulation:
  def __init__(self,agent):
    self.agent=agent
    self.simulation_history=[]
  def start(self,num_steps):
      self.num_steps=num_steps
      print("\nStarting VaccumCleaner Simulation...")
      print("-----------------------------------")

      for step in range(num_steps):
          current_location = self.agent.location
          current_percept = self.agent.sensors()
          chosen_action = self.agent.choose_action()

    # Record current state before action
          step_details = {
              'step': step + 1,
              'location_before_action': current_location,
              'percept': current_percept,
              'action': chosen_action,
              'environment_before_action': self.agent.environment.copy()
          }

          print(f"\n--- Step {step + 1} ---")
          print(f"Current Location: {current_location}")
          print(f"Percept (State of {current_location}): {current_percept}")
          print(f"Chosen Action: {chosen_action}")

          if chosen_action == 'clean':
              self.agent.clean()
          else:
              self.agent.move()

          step_details['location_after_action'] = self.agent.location
          step_details['environment_after_action'] = self.agent.environment.copy()
          self.simulation_history.append(step_details)
          print("Simulation Finished.")


  def history(self):
    print("\n-----------------------------------")
    print("\nSimulation History:")
    for record in self.simulation_history:
      print(f"\nStep {record['step']}:")
      print(f"  Location (Before Action): {record['location_before_action']}")
      print(f"  Percept: {record['percept']}")
      print(f"  Action: {record['action']}")
      print(f"  Environment (Before Action): {record['environment_before_action']}")
      print(f"  Location (After Action): {record['location_after_action']}")
      print(f"  Environment (After Action): {record['environment_after_action']}")

vaccum_simulation=simulation(my_vaccum)
vaccum_simulation.start(10)

vaccum_simulation.history()

