# -*- coding: utf-8 -*-
"""Lab3_Q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YUtUMpBe-zh4KgeVfoU2or1-twyFx1yK
"""

class Railway_agent:
    def __init__(self, environment_dict, rule_table):
        self.cost = 0
        self.rule_table = rule_table
        self.environment = environment_dict

    def percept(self):

        inbound = self.environment["inbound"]
        outbound = self.environment["outbound"]
        obstacle = self.environment["obstacle"]
        manual = self.environment["manual"]
        return (inbound, outbound, obstacle, manual)

    def choose_action(self):
        current_percept = self.percept()
        self.chosen_action = self.rule_table.get(current_percept, 'emergency')
        return self.chosen_action

    def after_action_to_environment(self, gate_arm_val, siren_val, signal_val):
        self.environment["Gate_Arm"] = gate_arm_val
        self.environment["Siren"] = siren_val
        self.environment["Signal"] = signal_val

    def train_incoming_effect(self):
        self.after_action_to_environment(1, 1, 0) # Gate Lowered, Siren On, Signal Green

    def train_gone_effect(self):
        self.after_action_to_environment(0, 0, 1) # Gate Raised, Siren Off, Signal Red

    def emergency_effect(self):
        self.after_action_to_environment(1, 1, 1)

    def emergency_stop_effect(self):
        self.after_action_to_environment(1, 1, 1) # Gate Lowered, Siren On, Signal Red (Emergency Stop)

    def none_effect(self):
        # For 'NONE', assume safe state (gates raised, siren off, signal red)
        self.after_action_to_environment(0, 0, 1)

    def execute_chosen_action(self): # Renamed from 'execute'
        if self.chosen_action == 'train_incoming':
            self.train_incoming_effect()
        elif self.chosen_action == 'train_gone':
            self.train_gone_effect()
        elif self.chosen_action == 'emergency':
            self.emergency_effect()
        elif self.chosen_action == 'EMERGENCY_STOP':
            self.emergency_stop_effect()
        elif self.chosen_action == 'NONE':
            self.none_effect()

class Simulation:
    def __init__(self, agent):
        self.agent = agent
        self.simulation_history = []

    def start(self, scenarios):
        print("Starting Railway Crossing Simulation...")
        print("-----------------------------------")

        for step, scenario_percepts in enumerate(scenarios):
            # Update the environment with the current scenario's percepts
            self.agent.environment["inbound"] = scenario_percepts["inbound"]
            self.agent.environment["outbound"] = scenario_percepts["outbound"]
            self.agent.environment["obstacle"] = scenario_percepts["obstacle"]
            self.agent.environment["manual"] = scenario_percepts["manual"]

            current_percept_tuple = self.agent.percept()
            chosen_action = self.agent.choose_action()

            # Record current state before action
            step_details = {
                'step': step + 1,
                'percept': current_percept_tuple,
                'chosen_action_name': chosen_action,
                'environment_before_action': self.agent.environment.copy()
            }

            print(f"\n--- Step {step + 1} ---")
            print(f"Percept (In, Out, Obs, Man): {current_percept_tuple}")
            print(f"Chosen Action: {chosen_action}")

            self.agent.execute_chosen_action()

            step_details['environment_after_action'] = self.agent.environment.copy()
            self.simulation_history.append(step_details)

            print(f"  Environment State (After Action): Gate_Arm={self.agent.environment['Gate_Arm']}, Siren={self.agent.environment['Siren']}, Signal={self.agent.environment['Signal']}")

        print("\nSimulation Finished.")

    def history(self):
        print("\n-----------------------------------")
        print("Simulation History:")
        for record in self.simulation_history:
            print(f"\nStep {record['step']}:")
            print(f"  Percept: {record['percept']}")
            print(f"  Chosen Action: {record['chosen_action_name']}")
            print(f"  Environment (Before Action): {record['environment_before_action']}")
            print(f"  Environment (After Action): {record['environment_after_action']}")

# Rules: (In, Out, Box, Man)

ruletable = {
    # Manual Emergency (High Priority)
    (1, 0, 0, 1): 'emergency',
    (0, 0, 0, 1): 'emergency',
    (1, 0, 1, 1): 'emergency',

    # Obstacle detected while train is coming
    (1, 0, 1, 0): 'EMERGENCY_STOP',

    # Train is coming (Inbound)
    (1, 0, 0, 0): 'train_incoming',

    # Train is passing/gone (Outbound hits)
    (0, 1, 0, 0): 'train_gone',
    (1, 1, 0, 0): 'train_gone',

    # No train, but obstacle detected (SAFETY CRITICAL)
    (0, 0, 1, 0): 'emergency', # Changed from 'NONE' to 'emergency' for safety

    # No train/Idle
    (0, 0, 0, 0): 'NONE'
}

Environment={
    "Gate_Arm": 0,      # 0 = Safe/Pass/Raise, 1 = Alert/Stop/Lower
    "Siren": 0,
    "Signal": 1,        # Signal is Red (1) by default for safety
    "inbound": 0,
    "outbound": 0,
    "obstacle": 0,
    "manual": 0
}

scenarios = [
    ("Clear Path", (0, 0, 0)),
    ("Normal Train Approaching", (1, 0, 0)),
    ("Obstacle on Tracks, No Train", (0, 1, 0)),
    ("Emergency Activation, No Train/Obstacle", (0, 0, 1)),
    ("Train Approaching, Obstacle on Tracks", (1, 1, 0)),
    ("Emergency + Train Approaching", (1, 0, 1)),
    ("Obstacle on Tracks + Emergency", (0, 1, 1)),
    ("All Conditions (Train, Obstacle, Emergency)", (1, 1, 1))
]

# Make sure Environment and ruletable are defined (from previous cells)
# Environment (cell SwHsDA3ks-CK)
# ruletable (cell Eh9MC8dywRcL)

# Instantiate the Railway_agent
agent = Railway_agent(Environment, ruletable)

# Define scenarios for the simulation
# Each scenario is a dictionary representing the state of inbound, outbound, obstacle, and manual sensors
scenarios = [
    {"inbound": 0, "outbound": 0, "obstacle": 0, "manual": 0}, # 1. Initial State / No Train / Clear / No Manual
    {"inbound": 1, "outbound": 0, "obstacle": 0, "manual": 0}, # 2. Train Incoming / Clear / No Manual
    {"inbound": 1, "outbound": 0, "obstacle": 1, "manual": 0}, # 3. Train Incoming / Obstacle / No Manual
    {"inbound": 0, "outbound": 1, "obstacle": 0, "manual": 0}, # 4. Train Gone / Clear / No Manual
    {"inbound": 0, "outbound": 0, "obstacle": 1, "manual": 0}, # 5. No Train / Obstacle / No Manual
    {"inbound": 0, "outbound": 0, "obstacle": 0, "manual": 1}, # 6. No Train / Clear / Manual Active
    {"inbound": 1, "outbound": 0, "obstacle": 0, "manual": 1}  # 7. Train Incoming / Clear / Manual Active
]

# Instantiate and run the Simulation
sim = Simulation(agent)
sim.start(scenarios)

sim.history()

