# -*- coding: utf-8 -*-
"""Lab1_q2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a5DXFbS6EAvqJnYn58gGAGhMGxuY5l-r
"""

from collections import defaultdict

graph = defaultdict(list)#Create empty list if key doesn't exist key

# dir 1 f1->f2
# dir 2 f2->f1
# dir 3 f1<->f2
def connect(f1,f2,dir):
  if(dir == 1):
    graph[f1].append(f2)
  elif(dir == 2):
    graph[f2].append(f1)
  else:
    graph[f1].append(f2)
    graph[f2].append(f1)

connect("Sunil","Raj",3)
connect("Sunil","Akash",3)
connect("Sunil","Sneha",3)
connect("Sunil","Maya",3)

connect("Raj","Neha_c",3)
connect("Raj","Priya",2)
connect("Akash","Priya",3)
connect("Akash","Neha_c",2)
connect("Sneha","Neha_c",3)
connect("Sneha","Rahul",3)
connect("Maya","Arjun_c",3)
connect("Maya","Rahul",1)

connect("Priya","Neha_r",2)
connect("Priya","Arav",1)
connect("Neha_c","Arav",3)
connect("Neha_c","Neha_r",2)
connect("Neha_c","Rahul",2)
connect("Rahul","Neha_r",3)
connect("Rahul","Arjun_r",3)
connect("Rahul","Pooja",3)
connect("Arjun_c","Pooja",3)


connect("Arav","Arjun_r",3)
connect("Neha_r","Arav",3)
connect("Neha_r","Arjun_r",2)
connect("Pooja","Arjun_r",3)

"""* BFS TRAVERSAL"""

from queue import Queue
def bfstree(graph,s):
  visited = set([s])
  parent = {s : None}
  q = Queue()
  q.put(s)
  while not q.empty():
    n=q.get()#remove and return element from queue
    for neighbours in graph[n]:
      if neighbours not in visited:
        visited.add(neighbours)
        parent[neighbours]=n
        q.put(neighbours)
  return parent

"""* DFS Traversal"""

def dfstree(graph,s):
  visited = set()
  parent={}

  def dfs(a,b):
    visited.add(a)
    parent[a] = b
    for neighbours in graph[a]:
      if neighbours not in visited:
        dfs(neighbours,a)
  dfs(s,None)
  return parent

#display graph
def display_g(graph):
  for i in graph:
     print(i, "->", graph[i])

start = "Neha_c"

#traversal:
print("\nBFS Tree =\n")
bfs = bfstree(graph, start)
for i in bfs:
    print(f"{bfs[i]} -> {i}")

print("\nDFS Tree =\n")
dfs = dfstree(graph, start)
for i in dfs:
    print(f"{dfs[i]} -> {i}")